name: Tomasuh
markdown: Kramdown
#markdown: Redcarpet
highlighter: rouge
#url: http://0.0.0.0:4000 #domain
url: //tomasuh.github.io
paginate: 8
description:     Tomasuh 
intro:	Security oriented blog
logo:             logo.png
disqus_shortname: tomasuh
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           Tomasuh
  avatar:         <avatar-image-link>
  email:          tomasuh@tomasuh.com
  # Social networking links used in footer. Update and remove as you like.
  #twitter:
  github: https://github.com/Tomasuh
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true


gems: [jekyll-paginate]